services:
  proxy:
    image: traefik:2.9.1
    command:
      - --entryPoints.http.address=:80
      - --providers.docker=true
    ports: ["80:80"]
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  whoami:
    image: containous/whoami:v1.5.0
    labels:
      - traefik.enable
      - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)